### ISSUE TITLE
Expose the margins, preserve vertex colors

### ISSUE THREAD

**Issue by PhantomFighter** [TheStrokeForge/Vox-Cleaner-V2#1]
Very nice tool. I would use this if the margins were exposed (baking and packing) and make them adjustable in pixels units. Packing the UVs right up against the border of the texture poses some problems too. The ability to choose a resolution would be ideal as an additional option. While not a big deal, Mini should not be the default (in my opinion) even though most modern devices can handle non power of two textures. An argument can be made for performance on older devices, there is a measurable difference - but this will vary from gpu to gpu.

Also, tool doesn't work in Blender 3.5, 'pixel_snap_mode' needs to be renamed to 'pixel_round_mode'. I'm not sure when they renamed it, maybe 3.3 or 3.4, but that's an easy check/fix.

Edit2: As a workaround I'm using UV Pack Master to re-pack UVs in a more optimized way with margins, then baking with your tool, this works ok.

**Comment by TheStrokeForge** [comment]
Thanks so much! I'd love to add a variable pixel unit margin, but I haven't been able to figure out the math to do the same.
Adding a custom margin option is relatively easy. would do that in the next to be version.

I fixed the 'pixel_snap_mode' bug already on Gumroad! It's up as Vox Cleaner V2.1

I'll check out the addon UV pack master! Does it provide crisper margins?
