### ISSUE TITLE
Black lines

### ISSUE THREAD

**Issue by opizxiopzxiocpzxiop** [TheStrokeForge/Vox-Cleaner-V2#2]
Used this plugin and came across this problem: some models (not all) have black lines on the sides or somewhere else. Is there a way to fix this?
![blender_CIHRBiJi9g](https://github.com/TheStrokeForge/Vox-Cleaner-V2/assets/83085974/a2e949f0-8d25-4410-b18b-c9cd59775337)
Used this plugin and came across this problem: some models (not all) have black lines on the sides or somewhere else. Is there a way to fix this?
As I understand it, some parts of the model go beyond the texture and fall on a black field
![blender_1eHlI19lcE](https://github.com/TheStrokeForge/Vox-Cleaner-V2/assets/83085974/c673ab9b-7325-45b2-af48-2bf2dffeacf7)
Attempts to repair manually were unsuccessful.

**Comment by opizxiopzxiocpzxiop** [comment]
Just found a solution how to fix this. You need to go to the UV Editing tab, select the entire object in Edit Mode, press the right mouse button, Snap -> Selected to Pixels.
![blender_FM7mK0cAiL](https://github.com/TheStrokeForge/Vox-Cleaner-V2/assets/83085974/4025cdaf-82b2-4fd4-8c1e-51b58ce5a55c)
Thank you for such a great plugin, and especially Pixel Perfect!

**Comment by TheStrokeForge** [comment]
Hey there!

Hope you're doing great, and Thanks so much for reaching out.
So sorry for the inconvenience! Are you still facing the issue? If so, what
version of Blender are you using? What version of Vox Cleaner are you
using??

 Cheers and Happy Cleaning
Farhan
